version: "3"
services:

  #webserver
  nginx-php:
    build: ./dockers/phps
    container_name: docker-nginx
    hostname: docker-nginx
    restart: always
    ports:
          - "6080:80"
    links:
      - "mysql"
      - "redis"
    volumes:
      - $PWD/www:/var/www/html
      - $PWD/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf/nginx/conf.d:/etc/nginx/sites-enabled
      - $PWD/conf/php/conf.d:/usr/local/etc/php/conf.d
      - $PWD/conf/php/cron/root:/var/spool/cron/crontabs/root
      - $PWD/conf/php/supervisor/supervisord.conf:/etc/supervisord.conf
    tty: true

  # database
  mysql:
    image: mysql:5.7
    container_name: docker-mysql
    hostname: docker-mysql
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data/mysql:/var/lib/mysql
      - $PWD/conf/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root

  redis:
    image: redis:3
    container_name: docker-redis
    hostname: docker-redis
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
        - "6079:6379"